### ISSUE TITLE
allow ip addresses wrong

### ISSUE THREAD

**Issue by marcosw1** [GoogleCloudPlatform/compute-ansible-gluster#6]
The gluster.yml script includes the following:

        - allow 10.240.*

However, the gluster-clients.yml script creates clients in us-east1, which have the ip addresses 10.42.x.x.

It's probably worth adding mention of this to the README.md file as well; it mentions the zone parameter but not the ip address.

**Comment by viglesiasce** [comment]
In order to make it simpler when switching regions I just made it 10.*
